### ISSUE TITLE
[WARNING]: - do1jlr.dotfiles was NOT installed successfully: - sorry, do1jlr.dotfiles was not found on https://galaxy.ansible.com/api/.

### ISSUE THREAD

**Issue by austin-agronick** [chaos-bodensee/role_dotfiles#10]
Is dotfiles under a new name now? I am getting `[WARNING]: - do1jlr.dotfiles was NOT installed successfully: - sorry, do1jlr.dotfiles was not found on https://galaxy.ansible.com/api/.`

**Comment by DO1JLR** [comment]
Yess, you find it at https://galaxy.ansible.com/ui/standalone/roles/l3d/dotfiles
```
ansible-galaxy role install l3d.dotfiles
```

it changed from the ``do1jlr`` namespace to the ``l3d`` namespace.
